org: unwiredben
app: cors-proxy
service: cors-proxy

plugins:
  - serverless-offline

provider:
  name: aws
  timeout: 20
  httpApi:
    cors: true
    disableDefaultEndpoint: true
  region: us-east-1

functions:
  arduboy-cors-proxy:
    handler: handler.corsProxy
    events:
      - httpApi:
          path: '/arduboyGet'
          method: get
