org: unwiredben
app: cors-proxy
service: cors-proxy

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 20
  httpApi:
    cors: true
  region: eu-central-1

functions:
  arduboy-cors-proxy:
    handler: handler.corsProxy
    events:
      - httpApi:
          path: '/get'
          method: get
